services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./packages/api
          target: /app/packages/api
          ignore:
            - node_modules/
        - action: sync
          path: ./packages/web
          target: /app/packages/web
          ignore:
            - node_modules/
            - dist/
    ports:
      - 5173:5173
      - 3000:3000
    environment:
      NODE_ENV: development
      PUBLIC_API_PORT: 3000
      PUBLIC_WEB_API_URL: http://localhost:3000
    entrypoint: ./scripts/dev.sh
    profiles: [dev]
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_WEB_API_URL: http://localhost:5173/api
    develop:
      watch:
        - action: sync+restart
          path: ./Caddyfile
          target: /etc/caddy/Caddyfile
        - action: sync+restart
          path: ./packages/api
          target: /app/packages/api
          ignore:
            - node_modules/
        - action: rebuild
          path: ./packages/web
          target: /app/packages/web
          ignore:
            - node_modules/
            - dist/
    ports:
      - 5173:443
    environment:
      NODE_ENV: production
      PUBLIC_API_PORT: 3000
    entrypoint: ./scripts/prod.sh
    profiles: [prod]

  