services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    profiles: [dev, prod]
    volumes:
      - db:/var/lib/postgresql/data
  testdb:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
      PGPORT: 5433
    ports:
      - 5433:5433
    profiles: [dev, prod]
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: ./packages/api
          target: /app/packages/api
          ignore:
            - node_modules/
            - build/
            - migrations/
        - action: sync
          path: ./packages/web
          target: /app/packages/web
          ignore:
            - node_modules/
            - build/
    ports:
      - 5173:5173
      - 3000:3000
    environment:
      PUBLIC_API_PORT: 3000
      PUBLIC_WEB_API_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      TEST_DATABASE_URL: postgres://test:test@testdb:5433/postgres
    volumes:
      - ./packages/api/migrations:/app/packages/api/migrations
    profiles: [dev]
  prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
      args:
        PUBLIC_WEB_API_URL: http://localhost:5173/api
    develop:
      watch:
        - action: sync+restart
          path: docker/caddy/Caddyfile
          target: /etc/caddy/Caddyfile
        - action: sync+restart
          path: ./packages/api
          target: /app/packages/api
          ignore:
            - node_modules/
            - build/
            - migrations/
        - action: rebuild
          path: ./packages/web
          target: /app/packages/web
          ignore:
            - node_modules/
            - build/
    ports:
      - 5173:443
    environment:
      PUBLIC_API_PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./packages/api/migrations:/app/packages/api/migrations
    profiles: [prod]
volumes:
  db:
  