/**
 * @fileoverview Dynamically generates routes based on the file structure in the `pages` directory.
 *
 * This component uses Vite's `import.meta.glob` to import all files matching the pattern
 * `../../pages` and creates routes based on the file paths.
 *
 * The routes are generated by:
 * - Removing the `../../pages` prefix.
 * - Removing `/index.ts` for folder-based routing.
 * - Removing `.tsx` extension.
 * - Converting dynamic segments (e.g., `[id]` to `:id`).
 *
 * Each route is lazy-loaded using `React.lazy` for code-splitting.
 *
 * A fallback route is added to handle 404 errors by loading the `../../pages/404` component.
 *
 * @version 1.0.0
 * @date 2025-01-15
 * @author Ali Morshid
 *
 * @returns {JSX.Element} The `Routes` component containing all the dynamically generated routes.
 */

import React from 'react';
import { Route, Routes } from 'react-router-dom';
import toKebabCase from '../utils/toKebabCase';

const pages = import.meta.glob('../../pages/**/*.{ts,tsx}');

const getRoutes = () => {
  const routes = Object.keys(pages).map((path) => {
    const routePath = path
      .replace('../../pages', '') // Remove the "pages" prefix
      .replace(/\/index\.ts$/, '') // Remove "/index" for folder-based routing
      .replace(/\.tsx$/, '') // Remove ".tsx"
      .replace(/\[([^/]+)\]/g, ':$1'); // Convert dynamic segments

    // Lazy-load the component
    const Component = React.lazy(
      pages[path] as () => Promise<{ default: React.ComponentType }>,
    );

    return { path: toKebabCase(routePath) || '/', Component };
  });

  // Fallback route
  routes.push({
    path: '*',
    Component: React.lazy(() => import(`../../pages/404`)),
  });

  return routes;
};

const FileSystemRouter = () => {
  const routes = getRoutes();

  return (
    <Routes>
      {routes.map(({ path, Component }) => (
        <Route
          key={path}
          path={path}
          element={
            <React.Suspense fallback={<div>Loading...</div>}>
              <Component />
            </React.Suspense>
          }
        />
      ))}
    </Routes>
  );
};

export default FileSystemRouter;
